SUBDIRS = Window \
  				Split \
					Tabbed \
					TabbedWindow \
					SegmentedControl \
					ProgressIndicator \
					ListViewController \
					InfoBar \
					ActionBar \
					Popup

include ../buildsys.mk
