SUBDIRS = window        \
          button        \
          image         \
          scale         \
          progressbar   \
          spinner       \
          togglebutton  \
          checkbutton   \
          menu          \
          switch        \
          headerbar     \
					levelbar

include ../buildsys.mk
