SUBDIRS = window \
          button \
          image \
          scale \
          progressbar \
          spinner \
          togglebutton \
          checkbutton \
          menu \
          switch

include ../buildsys.mk
